default: &default
  adapter: postgresql #AQUII----------OLD: SQLITE3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_development

test:
  <<: *default
  database: my_test

production:
  <<: *default
  database: my_production
